version: "3.8"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    volumes: # https://docs.localstack.cloud/references/init-hooks/
      - ".localstack/bootstrap:/etc/localstack/init/ready.d/"
