name: "AWS EKS: kubectl cluster-info"

on:
  push:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:

  build:
    name: Get Cluster info
    runs-on: self-hosted
    environment: CI

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        shell: bash
        run: |
          set -eux
          cd "$(mktemp -d)"
          curl -sf "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Generate kubeconfig
        id: kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }} --region us-east-1

      - name: Get cluster info
        id: cluster-info
        run: |
          kubectl cluster-info
