---
name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    name: Build Image
    runs-on: self-hosted
    environment: CI

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install AWS CLI
        shell: bash
        run: |
          set -eux
          cd "$(mktemp -d)"
          curl -sf "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 385156030167.dkr.ecr.us-east-1.amazonaws.com/burnt/aa-api
          tags: |
            type=semver,pattern={{version}},priority=1000
            type=sha,priority=700

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: release

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Generate kubeconfig
        id: kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }} --region us-east-1

      - name: Install skaffold and tools
        shell: bash
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            gettext-base

      - name: Deploy to Kubernetes
        shell: bash
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail
          
          export IMAGE_TAG=sha-$(git rev-parse --short HEAD); \
          envsubst < ./manifests/testnet/deployment.yaml > ./manifests/testnet/deployment.temp.yaml; \
          cp ./manifests/testnet/deployment.yaml ./manifests/testnet/deployment.orig.yaml; \
          mv ./manifests/testnet/deployment.temp.yaml ./manifests/testnet/deployment.yaml; \
          pushd ./manifests/testnet; skaffold deploy; popd; \
          mv ./manifests/testnet/deployment.orig.yaml ./manifests/testnet/deployment.yaml;
